<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>BlocksOs.Api</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DocumentationFile>Api.xml</DocumentationFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DocumentationFile>Api.xml</DocumentationFile>
	</PropertyGroup>
	
	
  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" />
	<PackageReference Include="SeliseBlocks.Genesis.OS" />
	<PackageReference Include="SeliseBlocks.ConfigurationDriver" />
	<PackageReference Include="SeliseBlocks.ReleaseDriver.OS" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cloud.DomainService\Cloud.DomainService.csproj" />
    <ProjectReference Include="..\Cloud.LmtService\Cloud.LmtService.csproj" />
    <ProjectReference Include="..\Configuration.DomainService\Configuration.DomainService.csproj" />
    <ProjectReference Include="..\Identifier.DomainService\Identifier.DomainService.csproj" />
    <ProjectReference Include="..\Secrets.DomainService\Secrets.DomainService.csproj" />
  </ItemGroup>
</Project>
