import { Menu } from "@/models/menu-models";
import {
  BarChart3,
  Bell,
  BookMinus,
  // BrainCircuit, // Temporarily hidden (AI Models)
  Building2,
  CreditCard,
  Database,
  Fingerprint,
  GitBranch,
  Globe,
  Home,
  Key,
  // KeyRound, // Temporarily hidden (My Secret)
  Layers,
  // Link2, // Temporarily hidden (Magic URL)
  Lock,
  Mail,
  Package,
  ScrollText,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Users,
  Zap,
} from "lucide-react";

export const navigationMenus: Menu[] = [
  {
    id: "overview-project",
    type: "menu",
    name: "Overview",
    path: "/app/dashboard",
    icon: Home,
    desc: "Project overview and insights",
  },
  { type: "separator", id: "separator-overview" },
  {
    id: "environments",
    type: "menu",
    name: "Environments",
    path: "/app/project/environments",
    icon: Package,
    desc: "Manage project environments and configurations",
  },
  {
    id: "people",
    type: "menu",
    name: "People",
    path: "/app/project/people",
    icon: Users,
    desc: "Manage project members and permissions",
  },
  {
    id: "repositories",
    type: "menu",
    name: "Repositories",
    path: "/app/project/repositories",
    icon: BookMinus,
    desc: "Manage code repositories and integrations",
  },
  {
    id: "settings",
    type: "menu",
    name: "Project Settings",
    path: "/app/project/settings",
    icon: Settings,
    desc: "Configure project details and preferences",
  },
  {
    id: "subscription-usage",
    type: "menu",
    name: "Subscription Usage",
    path: "/app/project/subscription-usage",
    icon: CreditCard,
    desc: "View subscription details and usage metrics",
  },
  { type: "separator", id: "separator-identity" },
  {
    id: "service-identity__secret-management",
    type: "menu",
    name: "Secrets & Configs",
    path: "/app/secret-management",
    icon: Lock,
    desc: "Manage secrets, configs, and credentials",
    children: [
      // Temporarily hidden
      // {
      //   id: "my-secret",
      //   type: "menu",
      //   name: "My Secret",
      //   path: "/app/secret-management/my-secret",
      //   icon: KeyRound,
      //   desc: "Personal secrets and credentials",
      // },
      {
        id: "managed-services",
        type: "menu",
        name: "My Service",
        path: "/app/secret-management/managed-services",
        icon: Layers,
        desc: "Service-level secrets and configurations",
      },
      {
        id: "oidc",
        name: "OIDC",
        type: "menu",
        path: "/app/secret-management/oidc",
        icon: ShieldCheck,
        desc: "OpenID Connect configurations and clients",
      },
      {
        id: "client-credentials",
        name: "Client Credentials",
        path: "/app/secret-management/client-credentials",
        icon: Fingerprint,
        desc: "Manage client credentials and access tokens",
        type: "menu",
      },
      {
        id: "identity-providers",
        name: "Identity Provider",
        path: "/app/secret-management/identity-providers",
        icon: Building2,
        desc: "Configure identity providers and federation",
        type: "menu",
      },

      {
        id: "external-idp",
        name: "External IdP",
        path: "/app/secret-management/external-idp",
        icon: Globe,
        desc: "External identity providers & certificates",
        type: "menu",
      },
      {
        id: "captcha",
        name: "Captcha",
        path: "/app/secret-management/captcha",
        icon: ShieldAlert,
        desc: "Bot protection configuration",
        type: "menu",
      },
      {
        id: "mfa",
        name: "MFA",
        path: "/app/secret-management/mfa",
        icon: Smartphone,
        desc: "Multi-factor authentication settings",
        type: "menu",
      },
      // Temporarily hidden
      // {
      //   id: "magic-url",
      //   name: "Magic URL",
      //   path: "/app/secret-management/magic-url",
      //   icon: Link2,
      //   desc: "Password less magic link settings",
      //   type: "menu",
      // },
      {
        id: "email",
        name: "Email",
        path: "/app/secret-management/email",
        icon: Mail,
        desc: "Email provider configuration",
        type: "menu",
      },
      {
        id: "notification",
        name: "Notification",
        path: "/app/secret-management/notification",
        icon: Bell,
        desc: "Push & notification settings",
        type: "menu",
      },
      {
        id: "storage",
        name: "Storage",
        path: "/app/secret-management/storage",
        icon: Database,
        desc: "File and object storage",
        type: "menu",
      },
      // Temporarily hidden
      // {
      //   id: "ai-models",
      //   name: "AI Models",
      //   path: "/app/secret-management/ai-models",
      //   icon: BrainCircuit,
      //   desc: "AI model integrations",
      //   type: "menu",
      // },
    ],
  },
  {
    id: "service-identity__api-settings",
    type: "menu",
    name: "API Settings",
    path: "/app/api-settings",
    icon: Settings,
  },
  {
    id: "service-identity__authentication",
    type: "menu",
    name: "IDP",
    path: "/app/idp",
    icon: Key,
    children: [
      {
        id: "settings",
        name: "Settings",
        path: "/app/idp/settings",
        icon: SlidersHorizontal,
        desc: "Tenant IAM, auth, organization, and signup configuration",
        type: "menu",
      },

      // {
      //   id: "oidc-template",
      //   name: "OIDC Template",
      //   path: "/app/idp/oidc-template",
      //   icon: FileCode,
      //   desc: "Configure OIDC template",
      //   type: "menu",
      // },
      {
        id: "roles",
        name: "Roles",
        // Path is intentionally "role" (not "roles"): sidebar expansion uses
        // pathname.startsWith(menu.path), and detail pages live at
        // "/idp/role-detail/:id" which does not start with "/idp/roles".
        path: "/app/idp/role",
        icon: ShieldCheck,
        desc: "Manage roles",
        type: "menu",
      },
      {
        id: "permissions",
        name: "Permissions",
        // Path is intentionally "permission" (not "permissions"): sidebar expansion uses
        // pathname.startsWith(menu.path), and detail pages live at
        // "/idp/permission-detail/:id" which does not start with "/idp/permissions".
        path: "/app/idp/permission",
        icon: Lock,
        desc: "Manage permissions",
        type: "menu",
      },
    ],
  },
  { type: "separator", id: "separator-lmt" },
  {
    id: "service-identity__lmt",
    type: "menu",
    name: "LMT",
    path: "/app/lmt",
    icon: Zap,
    children: [
      {
        id: "usage",
        name: "Usage",
        path: "/app/lmt/usage",
        icon: BarChart3,
        desc: "Monitor API call metrics and performance",
        type: "menu",
      },
      {
        id: "tracing",
        name: "Tracing",
        path: "/app/lmt/tracing",
        icon: GitBranch,
        desc: "Trace requests across services",
        type: "menu",
      },
      {
        id: "logs",
        name: "Logs",
        path: "/app/lmt/logs",
        icon: ScrollText,
        desc: "Search and view application logs across your services",
        type: "menu",
      },
    ],
  },
];
