import { Menu } from "@/models/menu-models";
import {
  BarChart3,
  Bell,
  BookMinus,
  BrainCircuit,
  Building2,
  CreditCard,
  Database,
  FileCode,
  Fingerprint,
  GitBranch,
  Globe,
  ScrollText,
  Home,
  Key,
  KeyRound,
  Layers,
  Link2,
  Lock,
  Mail,
  Package,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Users,
  Zap,
} from "lucide-react";

export const navigationMenus: Menu[] = [
  {
    id: "overview-project",
    type: "menu",
    name: "Overview",
    path: "/dashboard",
    icon: Home,
    desc: "Project overview and insights",
  },
  {
    type: "separator",
    id: "separator-overview",
  },
  {
    id: "environments",
    type: "menu",
    name: "Environments",
    path: "/project-overview/environments",
    icon: Package,
    desc: "Manage project environments and configurations",
  },
  {
    id: "people",
    type: "menu",
    name: "People",
    path: "/project-overview/people",
    icon: Users,
    desc: "Manage project members and permissions",
  },
  {
    id: "repositories",
    type: "menu",
    name: "Repositories",
    path: "/project-overview/repositories",
    icon: BookMinus,
    desc: "Manage code repositories and integrations",
  },
  {
    id: "settings",
    type: "menu",
    name: "Project Settings",
    path: "/project-overview/settings",
    icon: Settings,
    desc: "Configure project details and preferences",
  },
  {
    id: "subscription-usage",
    type: "menu",
    name: "Subscription Usage",
    path: "/project-overview/subscription-usage",
    icon: CreditCard,
    desc: "View subscription details and usage metrics",
  },
  {
    type: "separator",
    id: "separator-identity",
  },
  {
    id: "service-identity__secret-management",
    type: "menu",
    name: "Secrets & Configs",
    path: "/services/secret-management",
    icon: Lock,
    desc: "Manage secrets, configs, and credentials",
    children: [
      {
        id: "my-secret",
        type: "menu",
        name: "My Secret",
        path: "/services/secret-management/my-secret",
        icon: KeyRound,
        desc: "Personal secrets and credentials",
      },
      {
        id: "managed-services",
        type: "menu",
        name: "My Service",
        path: "/services/secret-management/managed-services",
        icon: Layers,
        desc: "Service-level secrets and configurations",
      },
      {
        id: "oidc",
        name: "OIDC",
        type: "menu",
        icon: ShieldCheck,
        desc: "OpenID Connect configurations and clients",
        path: "/services/secret-management/oidc",
      },
      {
        id: "client-credentials",
        name: "Client Credentials",
        path: "/services/secret-management/client-credentials",
        icon: Fingerprint,
        desc: "Manage client credentials and access tokens",
        type: "menu",
      },
      {
        id: "identity-providers",
        name: "Identity Provider",
        path: "/services/secret-management/identity-providers",
        icon: Building2,
        desc: "Configure identity providers and federation",
        type: "menu",
      },
      {
        id: "sso",
        name: "SSO",
        path: "/services/secret-management/sso",
        icon: Users,
        desc: "Single sign-on configurations and social logins",
        type: "menu",
      },
      {
        id: "external-idp",
        name: "External IdP",
        path: "/services/secret-management/external-idp",
        icon: Globe,
        desc: "External identity providers & certificates",
        type: "menu",
      },
      {
        id: "captcha",
        name: "Captcha",
        path: "/services/secret-management/captcha",
        icon: ShieldAlert,
        desc: "Bot protection configuration",
        type: "menu",
      },
      {
        id: "mfa",
        name: "MFA",
        path: "/services/secret-management/mfa",
        icon: Smartphone,
        desc: "Multi-factor authentication settings",
        type: "menu",
      },
      {
        id: "magic-url",
        name: "Magic URL",
        path: "/services/secret-management/magic-url",
        icon: Link2,
        desc: "Passwordless magic link settings",
        type: "menu",
      },
      {
        id: "email",
        name: "Email",
        path: "/services/secret-management/email",
        icon: Mail,
        desc: "Email provider configuration",
        type: "menu",
      },
      {
        id: "notification",
        name: "Notification",
        path: "/services/secret-management/notification",
        icon: Bell,
        desc: "Push & notification settings",
        type: "menu",
      },
      {
        id: "storage",
        name: "Storage",
        path: "/services/secret-management/storage",
        icon: Database,
        desc: "File and object storage",
        type: "menu",
      },
      {
        id: "ai-models",
        name: "AI Models",
        path: "/services/secret-management/ai-models",
        icon: BrainCircuit,
        desc: "AI model integrations",
        type: "menu",
      },
    ],
  },
  {
    id: "service-identity__api-settings",
    type: "menu",
    name: "API Settings",
    path: "/services/api-settings",
    icon: Settings,
  },
  {
    id: "service-identity__authentication",
    type: "menu",
    name: "IDP",
    path: "/services/authentication",
    icon: Key,
    children: [
      {
        id: "config",
        name: "Settings",
        path: "/services/authentication/config",
        icon: SlidersHorizontal,
        desc: "Tenant IAM, auth, organization, and signup configuration",
        type: "menu",
      },
      {
        id: "oidc-template",
        name: "OIDC Template",
        path: "/services/authentication/oidc-template",
        icon: FileCode,
        desc: "Configure OIDC template",
        type: "menu",
      },
      {
        id: "roles",
        name: "Roles",
        path: "/services/authentication/roles",
        icon: ShieldCheck,
        desc: "Manage roles",
        type: "menu",
      },
      {
        id: "permissions",
        name: "Permissions",
        path: "/services/authentication/permissions",
        icon: Lock,
        desc: "Manage permissions",
        type: "menu",
      },
    ],
  },

  {
    type: "separator",
    id: "separator-lmt",
  },
  {
    id: "service-identity__lmt",
    type: "menu",
    name: "LMT",
    path: "/services/lmt",
    icon: Zap,
    children: [
      {
        id: "usage",
        name: "Usage",
        path: "/services/lmt/usage",
        icon: BarChart3,
        desc: "Monitor API call metrics and performance",
        type: "menu",
      },
      {
        id: "tracing",
        name: "Tracing",
        path: "/services/lmt/tracing",
        icon: GitBranch,
        desc: "Trace requests across services",
        type: "menu",
      },
      {
        id: "logs",
        name: "Logs",
        path: "/services/lmt/logs",
        icon: ScrollText,
        desc: "Search and view application logs across your services",
        type: "menu",
      },
    ],
  },
];
