import { Menu } from "@/models/menu-models";
import {
  BarChart3,
  Bell,
  BookMinus,
  BrainCircuit,
  Building2,
  CreditCard,
  Database,
  Fingerprint,
  GitBranch,
  Globe,
  Home,
  Key,
  KeyRound,
  Layers,
  Link2,
  Lock,
  Mail,
  Package,
  ScrollText,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Users,
  Zap,
} from "lucide-react";

export const navigationMenus: Menu[] = [
  {
    id: "overview-project",
    type: "menu",
    name: "Overview",
    path: "/app/dashboard",
    icon: Home,
    desc: "Project overview and insights",
  },
  { type: "separator", id: "separator-overview" },
  {
    id: "environments",
    type: "menu",
    name: "Environments",
    path: "/app/project/environments",
    icon: Package,
    desc: "Manage project environments and configurations",
  },
  {
    id: "people",
    type: "menu",
    name: "People",
    path: "/app/project/people",
    icon: Users,
    desc: "Manage project members and permissions",
  },
  {
    id: "repositories",
    type: "menu",
    name: "Repositories",
    path: "/app/project/repositories",
    icon: BookMinus,
    desc: "Manage code repositories and integrations",
  },
  {
    id: "settings",
    type: "menu",
    name: "Project Settings",
    path: "/app/project/settings",
    icon: Settings,
    desc: "Configure project details and preferences",
  },
  {
    id: "subscription-usage",
    type: "menu",
    name: "Subscription Usage",
    path: "/app/project/subscription-usage",
    icon: CreditCard,
    desc: "View subscription details and usage metrics",
    disabled: true, // Temporarily disabled
  },
  { type: "separator", id: "separator-identity" },
  {
    id: "service-identity__secret-management",
    type: "menu",
    name: "Secrets & Configs",
    path: "/app/secret-management",
    icon: Lock,
    desc: "Manage secrets, configs, and credentials",
    children: [
      {
        id: "secret-management",
        type: "menu",
        name: "Secret",
        path: "/app/secret-management/secret",
        icon: KeyRound,
        desc: "Securely manage API and service secrets for this environment",
        disabled: true, // Temporarily disabled
      },
      {
        id: "my-services",
        type: "menu",
        name: "My Services",
        path: "/app/secret-management/my-services",
        icon: Layers,
        desc: "Service-level secrets and configurations",
      },
      {
        id: "oidc",
        name: "OIDC",
        type: "menu",
        path: "/app/secret-management/oidc",
        icon: ShieldCheck,
        desc: "OpenID Connect configurations and clients",
      },
      {
        id: "client-credentials",
        name: "Client Credentials",
        path: "/app/secret-management/client-credentials",
        icon: Fingerprint,
        desc: "Manage client credentials and access tokens",
        type: "menu",
      },
      {
        id: "identity-providers",
        name: "Identity Provider",
        path: "/app/secret-management/identity-providers",
        icon: Building2,
        desc: "Configure identity providers and federation",
        type: "menu",
      },

      {
        id: "external-idp",
        name: "External IdP",
        path: "/app/secret-management/external-idp",
        icon: Globe,
        desc: "External identity providers & certificates",
        type: "menu",
      },
      {
        id: "captcha",
        name: "Captcha",
        path: "/app/secret-management/captcha",
        icon: ShieldAlert,
        desc: "Bot protection configuration",
        type: "menu",
      },
      {
        id: "mfa",
        name: "MFA",
        path: "/app/secret-management/mfa",
        icon: Smartphone,
        desc: "Multi-factor authentication settings",
        type: "menu",
      },

      {
        id: "magic-url",
        name: "Magic URL",
        path: "/app/secret-management/magic-url",
        icon: Link2,
        desc: "Password less magic link settings",
        type: "menu",
        disabled: true, // Temporarily disabled
      },
      {
        id: "email",
        name: "Email",
        path: "/app/secret-management/email",
        icon: Mail,
        desc: "Email provider configuration",
        type: "menu",
      },
      {
        id: "notification",
        name: "Notification",
        path: "/app/secret-management/notification",
        icon: Bell,
        desc: "Push & notification settings",
        type: "menu",
      },
      {
        id: "storage",
        name: "Storage",
        path: "/app/secret-management/storage",
        icon: Database,
        desc: "File and object storage",
        type: "menu",
      },
      {
        id: "ai-models",
        name: "AI Models",
        path: "/app/secret-management/ai-models",
        icon: BrainCircuit,
        desc: "AI model integrations",
        type: "menu",
        disabled: true, // Temporarily disabled
      },
    ],
  },
  {
    id: "service-identity__api-settings",
    type: "menu",
    name: "API Settings",
    path: "/app/api-settings",
    icon: Settings,
    desc: "Manage API keys and settings",
    disabled: true, // Temporarily disabled
  },
  {
    id: "service-identity__email-management",
    type: "menu",
    name: "Email Management",
    path: "/app/email-management",
    icon: Mail,
    desc: "Manage email templates and mailbox activity",
  },
  {
    id: "service-identity__authentication",
    type: "menu",
    name: "Identity & Access",
    path: "/app/iam",
    icon: Key,
    children: [
      {
        id: "settings",
        name: "Settings",
        path: "/app/iam/settings",
        icon: SlidersHorizontal,
        desc: "Tenant IAM, auth, organization, and signup configuration",
        type: "menu",
      },

      {
        id: "users",
        name: "Users",
        // Path is intentionally "user" (not "users"): sidebar expansion uses
        // pathname.startsWith(menu.path), and detail pages live at
        // "/iam/user-detail/:id" which does not start with "/iam/users".
        path: "/app/iam/user",
        icon: Users,
        desc: "Manage users",
        type: "menu",
      },
      {
        id: "organizations",
        name: "Organizations",
        // Path is intentionally "organization" (not "organizations"): sidebar expansion uses
        // pathname.startsWith(menu.path), and detail pages live at
        // "/iam/organization-detail/:orgId" which does not start with "/iam/organizations".
        path: "/app/iam/organization",
        icon: Building2,
        desc: "Manage organizations",
        type: "menu",
      },
      {
        id: "roles",
        name: "Roles",
        // Path is intentionally "role" (not "roles"): sidebar expansion uses
        // pathname.startsWith(menu.path), and detail pages live at
        // "/iam/role-detail/:id" which does not start with "/iam/roles".
        path: "/app/iam/role",
        icon: ShieldCheck,
        desc: "Manage roles",
        type: "menu",
      },
      {
        id: "permissions",
        name: "Permissions",
        // Path is intentionally "permission" (not "permissions"): sidebar expansion uses
        // pathname.startsWith(menu.path), and detail pages live at
        // "/iam/permission-detail/:id" which does not start with "/iam/permissions".
        path: "/app/iam/permission",
        icon: Lock,
        desc: "Manage permissions",
        type: "menu",
      },
    ],
  },
  { type: "separator", id: "separator-lmt" },
  {
    id: "service-identity__lmt",
    type: "menu",
    name: "Logs & Traces",
    path: "/app/lmt",
    icon: Zap,
    children: [
      {
        id: "usage",
        name: "Usage",
        path: "/app/lmt/usage",
        icon: BarChart3,
        desc: "Monitor API call metrics and performance",
        type: "menu",
      },
      {
        id: "tracing",
        name: "Tracing",
        path: "/app/lmt/tracing",
        icon: GitBranch,
        desc: "Trace requests across services",
        type: "menu",
      },
      {
        id: "logs",
        name: "Logs",
        path: "/app/lmt/logs",
        icon: ScrollText,
        desc: "Search and view application logs across your services",
        type: "menu",
      },
    ],
  },
];
