#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");
const ts = require("typescript");
const {
  e2eRoot,
  flowGraphPath,
  flowGraphMdPath,
  selectorIndexPath,
  printVerdict,
  readJson,
  writeJson,
  repoRelative,
  toPosix,
} = require("./lib/common");

const selectorSourceDirs = [path.join(e2eRoot, "tests"), path.join(e2eRoot, "support")];

function listTsFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listTsFiles(fullPath));
    else if (entry.isFile() && entry.name.endsWith(".ts")) out.push(fullPath);
  }
  return out;
}

function attrText(node) {
  if (!node) return undefined;
  if (ts.isStringLiteralLike(node)) return node.text;
  if (ts.isJsxExpression(node) && node.expression && ts.isStringLiteralLike(node.expression)) {
    return node.expression.text;
  }
  return undefined;
}

function collectSelectors(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const sf = ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const selectors = [];

  function add(kind, value, node) {
    if (!value || value.length > 160) return;
    selectors.push({
      file: repoRelative(filePath),
      kind,
      value,
      line: sf.getLineAndCharacterOfPosition(node.getStart(sf)).line + 1,
    });
  }

  function propertyValue(objectNode, name) {
    if (!ts.isObjectLiteralExpression(objectNode)) return undefined;
    for (const prop of objectNode.properties) {
      if (!ts.isPropertyAssignment(prop)) continue;
      const propName = prop.name.getText(sf).replace(/^["']|["']$/g, "");
      if (propName === name && ts.isStringLiteralLike(prop.initializer)) return prop.initializer.text;
    }
    return undefined;
  }

  function walk(node) {
    if (ts.isCallExpression(node)) {
      const callee = node.expression.getText(sf);
      const method = callee.split(".").pop();
      if (["getByText", "getByLabel", "getByPlaceholder"].includes(method)) {
        const first = node.arguments[0];
        if (first && ts.isStringLiteralLike(first)) add(method, first.text, node);
      }
      if (method === "getByRole" && node.arguments[1]) {
        const name = propertyValue(node.arguments[1], "name");
        if (name) add("getByRole.name", name, node);
      }
      if (method === "waitForURL") {
        const first = node.arguments[0];
        if (first && ts.isStringLiteralLike(first)) add("waitForURL", first.text, node);
      }
    }
    ts.forEachChild(node, walk);
  }

  walk(sf);
  return selectors;
}

function sourceFileStats(files) {
  return files.map((filePath) => {
    const stat = fs.statSync(filePath);
    return {
      path: repoRelative(filePath),
      mtimeMs: stat.mtimeMs,
      size: stat.size,
    };
  });
}

function renderMermaid(graph) {
  const lines = [
    "# E2E Flow Graph",
    "",
    "Generated by `npm run graph:render` - do not hand-edit.",
    "",
    "```mermaid",
    "graph LR",
  ];

  for (const node of graph.nodes) {
    lines.push(`  ${node.id}["${String(node.label || node.id).replace(/"/g, '\\"')}"]`);
  }

  for (const edge of graph.edges) {
    lines.push(`  ${edge.from} -->|"${String(edge.action || edge.id).replace(/"/g, '\\"')}"| ${edge.to}`);
  }

  lines.push("```", "");
  lines.push(`Nodes: ${graph.nodes.length}`);
  lines.push(`Edges: ${graph.edges.length}`);
  lines.push("");
  return lines.join("\n");
}

try {
  const graph = readJson(flowGraphPath);
  fs.mkdirSync(path.dirname(flowGraphMdPath), { recursive: true });
  fs.writeFileSync(flowGraphMdPath, renderMermaid(graph));

  const sourceFiles = selectorSourceDirs.flatMap(listTsFiles).sort();
  const selectors = sourceFiles.flatMap(collectSelectors);
  writeJson(selectorIndexPath, {
    metadata: {
      generatedAt: new Date().toISOString(),
      sourceFiles: sourceFileStats(sourceFiles),
    },
    selectors,
  });

  printVerdict(
    "pass",
    `generated flow graph documentation and ${selectors.length} selector index entries`,
    "none",
    [`selectorIndex: ${toPosix(path.relative(e2eRoot, selectorIndexPath))}`],
  );
} catch (error) {
  printVerdict("fail", `render failed: ${error.message}`, "fix render error");
  process.exitCode = 1;
}
