<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	  <!--<PackageReference Include="Azure.Identity" />-->
	  <PackageReference Include="Azure.ResourceManager.ServiceBus" />
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="MongoDB.Driver" />
	  <PackageReference Include="SeliseBlocks.Genesis.OS" />
	  <PackageReference Include="SeliseBlocks.MailDriver.OS" />
	  <PackageReference Include="SeliseBlocks.StorageDriver.OS" />
   <PackageReference Include="MimeKit" />
   <PackageReference Include="MailKit" />
	  <PackageReference Include="SixLabors.Fonts" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>



</Project>
