export const SERVICES = [
  // {
  //   label: "Identity",
  //   name: "idp",
  //   serviceName: "idp",
  //   showInUsage: true,
  //   showInTraces: true,
  //   showInLogs: true,
  // },
  // {
  //   label: "Authentication",
  //   name: "authentication",
  //   serviceName: "authentication",
  //   showInUsage: true,
  //   showInTraces: true,
  //   showInLogs: true,
  // },
  {
    label: "IAM",
    name: "iam",
    serviceName: "iam",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  // {
  //   label: "MFA",
  //   name: "mfa",
  //   serviceName: "mfa",
  //   showInUsage: true,
  //   showInTraces: true,
  //   showInLogs: true,
  // },
  // {
  //   label: "Captcha",
  //   name: "captcha",
  //   serviceName: "captcha",
  //   showInUsage: true,
  //   showInTraces: true,
  //   showInLogs: true,
  // },
  // {
  //   label: "Email",
  //   name: "email",
  //   serviceName: "communication",
  //   showInUsage: true,
  //   showInTraces: true,
  //   showInLogs: true,
  // },
  {
    label: "Data",
    name: "data",
    serviceName: "data",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  // {
  //   label: "Notification",
  //   name: "notification",
  //   serviceName: "notification",
  //   showInUsage: true,
  //   showInTraces: true,
  //   showInLogs: true,
  // },
  {
    label: "Localization",
    name: "localization",
    serviceName: "localization",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  {
    label: "AI Gateway",
    name: "ai",
    serviceName: "ai",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  {
    label: "OS",
    name: "os",
    serviceName: "os",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  {
    label: "Utilities",
    name: "utilities",
    serviceName: "utilities",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  {
    label: "Logic",
    name: "logic",
    serviceName: "logic",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  {
    label: "Monitor",
    name: "monitor",
    serviceName: "monitor",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  {
    label: "Release",
    name: "release",
    serviceName: "release",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  {
    label: "Studio",
    name: "studio",
    serviceName: "studio",
    showInUsage: true,
    showInTraces: true,
    showInLogs: true,
  },
  // {
  //   label: "Identifier",
  //   name: "identifier",
  //   serviceName: "identifier",
  //   showInUsage: false,
  //   showInTraces: true,
  //   showInLogs: false,
  // },
  // {
  //   label: "Configuration",
  //   name: "configuration",
  //   serviceName: "configuration",
  //   showInUsage: false,
  //   showInTraces: true,
  //   showInLogs: false,
  // },
  // {
  //   label: "LMT",
  //   name: "lmt",
  //   serviceName: "lmt",
  //   showInUsage: false,
  //   showInTraces: true,
  //   showInLogs: false,
  // },
] as const;

export type ServiceName = (typeof SERVICES)[number]["name"];
export type ServiceApiName = `blocks-${(typeof SERVICES)[number]["serviceName"]}-api`;
export type ServiceWorkerName = `blocks-${(typeof SERVICES)[number]["serviceName"]}-worker`;
