<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<!--<PackageReference Include="MongoDB.Driver" />-->
		<PackageReference Include="SeliseBlocks.Genesis.OS" Condition="'$(UseLocalGenesis)' != 'true'" />
		<ProjectReference Include="$(LocalGenesisProject)" Condition="'$(UseLocalGenesis)' == 'true'" />
		<PackageReference Include="SeliseBlocks.MailDriver.OS" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Parquet.Net" />
  <PackageReference Include="FluentValidation" />
	</ItemGroup>

</Project>
