import { DomainAction } from "@/pages/dashboard/components/domain";
import type { IProject as IPackageProject } from "@seliseblocks/genesis-os/models";
import type { ProjectType } from "@blocks-identifier/models/project.model";

/**
 * How a domain came to be on a project.
 *
 * - `PlatformSubdomain` — generated by Blocks: one per repository per environment, plus any
 *   host the customer registered that happens to sit under a platform domain.
 * - `Custom` — a domain the customer owns and pointed at the platform themselves.
 * - `Unspecified` — written before the field existed. Not a category: a project reads this way
 *   until it is backfilled, so never branch on it as though it meant something.
 *
 * `PlatformDefault` (the shared IAM and Studio hosts) is deliberately absent — the server keeps
 * those in every tenant's allow-list but never sends them here, because they belong to the
 * platform rather than to any one project.
 */
export type DomainType = "Unspecified" | "PlatformSubdomain" | "Custom";

/**
 * Declared here rather than imported from `@seliseblocks/genesis-os` so `domainType` can ship
 * without waiting on a package release. The overview page and everything it renders already
 * live in this repo; the package only supplied the type.
 */
export interface IDomain {
  domain: string;
  cookieDomain: string;
  isDomainVerified: boolean;
  domainType: DomainType;
}

/**
 * What the console may set on a domain. `domainType` is absent on purpose: the server derives
 * it from the host, so a caller cannot pass its own domain off as one of the platform's.
 */
export type IDomainRequest = Omit<IDomain, "domainType">;

/** The package's project, with the local {@link IDomain} in place of its own. */
export type IProject = Omit<IPackageProject, "applications"> & {
  applications: IDomain[];
  /** Gates Genesis third-party token trust for this tenant (Phase 1 Project/Get). */
  isThirdPartyJwtEnabled: boolean;
  /** The project's type. Only `Project/Get` returns it; project lists leave it out. */
  projectType?: ProjectType;
};

export interface IProjectGroup {
  tenantGroupId: string;
  projects: IProject[];
  nonSharedProject: IProject[];
  isShared: boolean;
  /**
   * The caller's grants in this group. Empty for a group they own — an owner holds everything
   * implicitly. Carried on the list so the console can tell whether a shared project has
   * anything to open without asking per card.
   */
  accessPolicies?: string[];
}

export interface IGetProjectResponse {
  data: IProject;
  errors: unknown | null;
}

export interface IUpdateProjectPayload {
  action: DomainAction;
  application: IDomainRequest;
  applicationDomain?: string;
  /**
   * Also tear down the shared API host under the cookie domain. It serves every
   * application under that domain — in this project and in others — so omitting
   * it (the default) keeps it running.
   */
  deleteSharedApiHost?: boolean;
}
export interface IUpdateProjectResponse {
  errors: unknown | null;
  isSuccess: boolean;
}
export interface IValidateCnameProjectPayload {
  cookieDomain: string;
}

export interface IRestoreProjectPayload {
  itemId: string;
}
export interface IRestoreProjectResponse {
  errors: unknown | null;
  isSuccess: boolean;
}
