using Blocks.Genesis;

namespace DomainService.Shared
{
    /// <summary>
    /// Everything the console needs to walk a customer through connecting their domains:
    /// the DNS records to create and the API base URL their app must call. Built on the server
    /// so the console never has to know the platform's CNAME label, target or default API host.
    /// </summary>
    public class DomainSetupGuideResponse : BaseResponse
    {
        public List<DomainSetupGuideItem> Applications { get; set; } = new();
    }

    public class DomainSetupGuideItem
    {
        /// <summary>The application's domain exactly as it is stored, so the console can match it to its row.</summary>
        public string Domain { get; set; } = string.Empty;
        public string CookieDomain { get; set; } = string.Empty;
        public bool IsDomainVerified { get; set; }

        /// <summary>Generated by the platform: always verified, needs no DNS records.</summary>
        public bool IsPlatformDomain { get; set; }

        /// <summary>The site host is the root of its DNS zone, where a CNAME is not allowed.</summary>
        public bool IsApex { get; set; }

        /// <summary>What the app deployed on this domain sets as its Blocks API URL.</summary>
        public string ApiBaseUrl { get; set; } = string.Empty;

        /// <summary>The records to create, app first. Empty for a platform domain.</summary>
        public List<DnsRecordInstruction> Records { get; set; } = new();
    }

    public class DnsRecordInstruction
    {
        /// <summary>"app" for the site host, "api" for the Blocks API host under it.</summary>
        public string Purpose { get; set; } = string.Empty;

        /// <summary>"CNAME", or "A" on an apex host ("ALIAS" when the target's IP could not be resolved).</summary>
        public string Type { get; set; } = string.Empty;

        /// <summary>The name relative to the DNS zone, as most providers want it ("@" for the root).</summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>The fully qualified host the record creates.</summary>
        public string Host { get; set; } = string.Empty;

        public string Value { get; set; } = string.Empty;
    }
}
