import { API_BASES } from "@/constants/endpoint.constant";

const STORAGE_SUBPATH = "/Storage";

// Storage Configuration endpoints
export const STORAGE_CONFIG_ENDPOINTS = {
  GET_CONFIGS: `/api${STORAGE_SUBPATH}/Gets`,
  SAVE_CONFIG: `/api${STORAGE_SUBPATH}/Save`,
  DELETE_CONFIG: `/api${STORAGE_SUBPATH}/Delete`,
} as const;

// Storage File endpoints
export const STORAGE_FILE_ENDPOINTS = {
  GET_FILE: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/GetFile`,
  DELETE_FILE: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/DeleteFile`,
  DELETE_FOLDER: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/DeleteFolder`,
  GET_PRESIGNED_URL: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/GetPreSignedUrlForUpload`,
  GET_FILES_INFO: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/GetFilesInfo`,
  UPDATE_FILE_ADDITIONAL_INFO: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/updateFileAdditionalInfo`,
  UPLOAD_TO_LOCAL_STORAGE: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/UploadFileToLocalStorage`,
  GET_DMS_FILE_AND_FOLDER: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/GetDmsFileAndFolder`,
  UPLOAD_DMS_FILE: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/UploadFile`,
  CREATE_FOLDER: `${API_BASES.LOGIC}${STORAGE_SUBPATH}/CreateFolder`,
  UPLOAD_PUBLIC_CERTIFICATE: `${API_BASES.LOGIC}/Certificate/UploadCertificate`,
} as const;
